### ISSUE TITLE
Submit & Cancel button should be inverted

### ISSUE THREAD

**Issue by MaxDaniels** [TheEmidee/UEGitHubTools#34]
![image](https://github.com/user-attachments/assets/4acf2a09-d69b-484e-9e71-792e30b4bd6d)

I'm pretty sure I've closed comments instead of submitting them.

**Comment by TheEmidee** [comment]
its the same as other windows in UE so I'd rather keep it like this

![image](https://github.com/user-attachments/assets/666d15a6-15a6-454d-b1c5-8f050aa6e35f)
